### ISSUE TITLE
No custom notifications received

### ISSUE THREAD

**Issue by meetdilip** [maateen/battery-monitor#41]
Hi, I have the following settings in GUI. But, till date ( after GUI is introduced ), I received no custom notifications. Only low battery warning is available. Or, whatever there was before GUI was introduced. Thanks.
![bm custom](https://cloud.githubusercontent.com/assets/6965443/24947081/f0805bc6-1f82-11e7-8077-a425b757cf8e.png)

**Comment by maateen** [comment]
Let me test it again please.

**Comment by meetdilip** [comment]
Any update on this. I was using Kodi, and there was not 30 % low battery notification as well. I managed to notice the 9 % critical notification sound. Can you add sound notifications ( opt in ) as well, please..

**Comment by maateen** [comment]
@meetdilip 
- I have pushed a new commit to **devel** branch. This should fix your issue. Though I haven't merged this with **master** branch, but you can test this from [here](https://github.com/maateen/battery-monitor/tree/devel#for-developers). Please let me know the updates.
- I have thought about your feature request. Some people wouldn't like it. But some people will like it absolutely. So how will it be if I introduce a new settings whether the user wanna hear a sound or not? Also, please open a new feature request issue so that I can add it to the [milestone v0.6](https://github.com/maateen/battery-monitor/milestone/2).
